### ISSUE TITLE
//default keys... (what are they)

### ISSUE THREAD

**Issue by ghost** [No-Half-Pixels/Fluent-Framework#36]
Something we are finding a bit difficult in Fluent Framework documentation is that you have arrays with

```
array(
    //...
```

or if that is not shown you have 

```
$sections = array(
    //...
```

Is there still documentation coming for these, or some reference of something that is not shown?

**Comment by leemason** [comment]
we have added those to only focus on the areas in the array that are important for the context they are used.

whenever you see //.. its because that part of the config has been detailed previously.

for $sections is in the $sections documentation, and for fields its under the main field documentation.
